name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: '*/30 * * * *' # The workflow will run every 30 seconds.
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo ${{github.event_name}}
      - name: Say hello
        run: echo "Hello world!"
