name: 05 - 2 - Filters Activity And Types

on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - 'main'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: PR to main branch is closed
        run: echo "Running whenever a PR is closed"
